return {
  -- {
  --   "nvim-treesitter/nvim-treesitter",
  --   tag = "v0.10.0",
  --   build = ":TSUpdate",
  --   dependencies = {
  --     "nvim-treesitter/nvim-treesitter-textobjects",
  --   },
  --   config = function()
  --     require("nvim-treesitter.configs").setup({
  --       ensure_installed = { "c", "lua", "cpp" },
  --       sync_install = false,
  --       auto_install = true,
  --
  --       highlight = {
  --         enable = true,
  --       },
  --
  --       incremental_selection = {
  --         enable = true,
  --         keymaps = {
  --           node_incremental = "v",
  --           node_decremental = "V",
  --           scope_incremental = false,
  --         }
  --       },
  --     })
  --
  --     -- Configuration to treat JSONC files as JSON
  --     vim.treesitter.language.register('json', 'jsonc')
  --   end,
  -- },
  -- {
  --   "nvim-treesitter/nvim-treesitter-textobjects",
  --   dependencies = { "nvim-treesitter/nvim-treesitter" },
  --   config = function()
  --     -- Call textobjects' own setup function
  --     require("nvim-treesitter-textobjects").setup({
  --       select = {
  --         enable = true,
  --         lookahead = true,
  --         include_surrounding_whitespace = false,
  --         keymaps = {
  --           ['af'] = '@function.outer',
  --           ['if'] = '@function.inner',
  --           ['ac'] = '@class.outer',
  --           ['ic'] = '@class.inner',
  --           ['is'] = '@assignment.inner',
  --           ['as'] = '@assignment.outer',
  --           ['ig'] = '@block.inner',
  --           ['ag'] = '@block.outer',
  --           ['ia'] = '@parameter.inner',
  --           ['aa'] = '@parameter.outer',
  --           ['ik'] = '@call.inner',
  --           ['ak'] = '@call.outer',
  --           ['i/'] = '@comment.inner',
  --           ['a/'] = '@comment.outer',
  --           ['ir'] = '@conditional.inner',
  --           ['ar'] = '@conditional.outer',
  --           ['io'] = '@loop.inner',
  --           ['ao'] = '@loop.outer',
  --           ['it'] = '@return.inner',
  --           ['at'] = '@return.outer',
  --         },
  --       },
  --       move = {
  --         enable = true,
  --         set_jumps = true,
  --         goto_next_start = {
  --           ["]f"] = "@function.outer",
  --           ["]c"] = "@class.outer",
  --           [']s'] = '@assignment.inner',
  --           [']g'] = '@block.outer',
  --           [']a'] = '@parameter.outer',
  --           [']k'] = '@call.outer',
  --           [']/'] = '@comment.outer',
  --           [']r'] = '@conditional.outer',
  --           [']o'] = '@loop.outer',
  --           [']t'] = '@return.outer'
  --         },
  --         goto_next_end = {
  --           ["]F"] = "@function.outer",
  --           ["]C"] = "@class.outer",
  --           [']S'] = '@assignment.inner',
  --           [']G'] = '@block.outer',
  --           [']A'] = '@parameter.outer',
  --           [']K'] = '@call.outer',
  --           [']?'] = '@comment.outer',
  --           [']R'] = '@conditional.outer',
  --           [']O'] = '@loop.outer',
  --           [']T'] = '@return.outer'
  --         },
  --         goto_previous_start = {
  --           ["[f"] = "@function.outer",
  --           ["[c"] = "@class.outer",
  --           ['[s'] = '@assignment.inner',
  --           ['[g'] = '@block.outer',
  --           ['[a'] = '@parameter.outer',
  --           ['[k'] = '@call.outer',
  --           ['[/'] = '@comment.outer',
  --           ['[r'] = '@conditional.outer',
  --           ['[o'] = '@loop.outer',
  --           ['[t'] = '@return.outer',
  --         },
  --         goto_previous_end = {
  --           ["[F"] = "@function.outer",
  --           ["[C"] = "@class.outer",
  --           ['[S'] = '@assignment.inner',
  --           ['[G'] = '@block.outer',
  --           ['[A'] = '@parameter.outer',
  --           ['[K'] = '@call.outer',
  --           ['[?'] = '@comment.outer',
  --           ['[R'] = '@conditional.outer',
  --           ['[O'] = '@loop.outer',
  --           ['[T'] = '@return.outer'
  --         },
  --       },
  --     })
  --   end,
  -- },
  -- { 
  --   "nvim-treesitter/nvim-treesitter-context",
  --   config = function()
  --     require("treesitter-context").setup({ enable = true, separator = " " })
  --   end,
  -- },
}